repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: end-of-file-fixer
      name: End-of-file fixer (non-Python)
      description: Ensures every *non-Python* file is empty or ends with a single newline
      exclude: ^.*\.(json|pyi?|py)$

    - id: trailing-whitespace
      name: Trailing-whitespace (non-Python)
      description: Trims trailing whitespace in non-Python text files
      exclude: ^.*\.(pyi?|py)$

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.13
  hooks:
    - id: ruff
      name: Ruff (lint + autofix)
      description: Fast Python linter (Flake8, isort, quotes, etc.) with --fix enabled
      args: [--fix]

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.7.13
  hooks:
    - id: uv-lock
      name: Make sure uv.lock file is up to date

- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.8.3
  hooks:
    - id: commitizen
    - id: commitizen-branch
      stages: [pre-push]
